spring:
    application:
        name: order-service
    profiles:
        group:
            dev: local-discovery, local-mq, local-db
---
spring:
    config:
        activate:
            on-profile: local-discovery
    cloud:
        config:
            discovery:
                enabled: true
                service-id: order-service
        discovery:
            enabled: true
eureka:
client:
    service-url:
        defaultZone: http://netflix:eureka@localhost:8761/eureka
logging:
    level:
        sql: debug
server:
    port: 8082
---
spring:
    config:
        activate:
            on-profile: local-mq
    artemis:
        user: artemis
        password: simetraehcapa
---
spring:
    config:
        activate:
            on-profile: local-db

    datasource:
        username: order_service
        password: password
        url: jdbc:mysql://127.0.0.1:3306/orderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        hikari:
            minimumIdle: 5
            maximumPoolSize: 20
            idle-timeout: 30000
            max-lifetime: 2000000
            connection-timeout: 30000

    jpa:
        database: mysql
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect