package com.maz.store.order.sm;

public enum OrderEvent {
    VALIDATE, PASS_VALIDATION, FAIL_VALIDATION,
    ALLOCATE, PASS_ALLOCATION, FAIL_ALLOCATION, DE_ALLOCATED,
    DELIVER, PICKED_UP, DELIVERED,
    CANCEL

}
